name: Vercel Notify on client changes

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'server/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'server/**'

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: 'notify vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - aerosol: client-deploy'
          github_token: ${{ secrets.GITHUB_TOKEN }}